import type { Project } from "@/types/project"

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Westfield Shopping Center",
    slug: "westfield-shopping-center",
    description: "A premier shopping destination with over 200 stores, restaurants, and entertainment options.",
    imageUrl: "https://images.unsplash.com/photo-1519567241046-7bc37b86e6a0?q=80&w=2865&auto=format&fit=crop",
    category: "Shopping Center",
    location: "San Francisco, CA",
    visitorCount: 1250000,
    storeCount: 215,
    rating: 4.7,
    createdAt: "2023-01-15T00:00:00Z",
    adminName: "John Smith",
    adminAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    floors: 4,
  },
  {
    id: "2",
    name: "Eastgate Mall",
    slug: "eastgate-mall",
    description: "A family-friendly mall featuring popular brands, a food court, and weekly events.",
    imageUrl: "https://images.unsplash.com/photo-1567449303078-57ad995bd17a?q=80&w=2787&auto=format&fit=crop",
    category: "Mall",
    location: "Chicago, IL",
    visitorCount: 980000,
    storeCount: 150,
    rating: 4.2,
    createdAt: "2023-03-22T00:00:00Z",
    adminName: "Sarah Johnson",
    adminAvatar: "https://randomuser.me/api/portraits/women/2.jpg",
    floors: 3,
  },
  {
    id: "3",
    name: "The Grand Plaza",
    slug: "the-grand-plaza",
    description: "An upscale shopping destination featuring luxury brands and fine dining experiences.",
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=2940&auto=format&fit=crop",
    category: "Shopping Center",
    location: "New York, NY",
    visitorCount: 1500000,
    storeCount: 180,
    rating: 4.8,
    createdAt: "2022-11-05T00:00:00Z",
    adminName: "Michael Brown",
    adminAvatar: "https://randomuser.me/api/portraits/men/3.jpg",
    floors: 5,
  },
  {
    id: "4",
    name: "Riverside Outlets",
    slug: "riverside-outlets",
    description: "An outdoor outlet mall offering discounted prices on popular brands.",
    imageUrl: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?q=80&w=2874&auto=format&fit=crop",
    category: "Outlet",
    location: "Orlando, FL",
    visitorCount: 850000,
    storeCount: 120,
    rating: 4.1,
    createdAt: "2023-05-18T00:00:00Z",
    adminName: "Emily Davis",
    adminAvatar: "https://randomuser.me/api/portraits/women/4.jpg",
    floors: 2,
  },
  {
    id: "5",
    name: "Metro Center",
    slug: "metro-center",
    description:
      "A modern shopping center located in the heart of downtown with excellent public transportation access.",
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?q=80&w=2940&auto=format&fit=crop",
    category: "Shopping Center",
    location: "Seattle, WA",
    visitorCount: 1100000,
    storeCount: 165,
    rating: 4.5,
    createdAt: "2023-02-10T00:00:00Z",
    adminName: "David Wilson",
    adminAvatar: "https://randomuser.me/api/portraits/men/5.jpg",
    floors: 3,
  },
  {
    id: "6",
    name: "Fashion District",
    slug: "fashion-district",
    description: "A trendy shopping destination focused on fashion, accessories, and beauty products.",
    imageUrl: "https://images.unsplash.com/photo-1549451371-64aa98a6f660?q=80&w=2940&auto=format&fit=crop",
    category: "Mall",
    location: "Los Angeles, CA",
    visitorCount: 1300000,
    storeCount: 190,
    rating: 4.6,
    createdAt: "2022-12-08T00:00:00Z",
    adminName: "Jennifer Martinez",
    adminAvatar: "https://randomuser.me/api/portraits/women/6.jpg",
    floors: 4,
  },
  {
    id: "7",
    name: "Northside Mall",
    slug: "northside-mall",
    description: "A community-focused mall with a mix of retail, dining, and entertainment options for all ages.",
    imageUrl: "https://images.unsplash.com/photo-1581417478175-a9ef18f210c2?q=80&w=2940&auto=format&fit=crop",
    category: "Mall",
    location: "Dallas, TX",
    visitorCount: 920000,
    storeCount: 140,
    rating: 4.0,
    createdAt: "2023-04-25T00:00:00Z",
    adminName: "Robert Taylor",
    adminAvatar: "https://randomuser.me/api/portraits/men/7.jpg",
    floors: 2,
  },
  {
    id: "8",
    name: "Luxury Square",
    slug: "luxury-square",
    description: "An exclusive shopping destination featuring high-end designer brands and premium services.",
    imageUrl: "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2940&auto=format&fit=crop",
    category: "Shopping Center",
    location: "Miami, FL",
    visitorCount: 750000,
    storeCount: 85,
    rating: 4.9,
    createdAt: "2023-01-30T00:00:00Z",
    adminName: "Amanda Garcia",
    adminAvatar: "https://randomuser.me/api/portraits/women/8.jpg",
    floors: 3,
  },
  {
    id: "9",
    name: "Central Department Store",
    slug: "central-department-store",
    description: "A historic department store offering a wide range of products across multiple floors.",
    imageUrl: "https://images.unsplash.com/photo-1574634534894-89d7576c8259?q=80&w=2864&auto=format&fit=crop",
    category: "Department Store",
    location: "Boston, MA",
    visitorCount: 680000,
    storeCount: 1,
    rating: 4.3,
    createdAt: "2023-03-05T00:00:00Z",
    adminName: "Thomas Anderson",
    adminAvatar: "https://randomuser.me/api/portraits/men/9.jpg",
    floors: 6,
  },
]
